# Generated by Django 5.1.5 on 2025-01-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
